-dontoptimize
-dontshrink
-keepattributes Exceptions,InnerClasses,Signature,Deprecated,SourceFile,LineNumberTable,*Annotation*,EnclosingMethod
-keepdirectories

-keeppackagenames com.eipl.amcs.*.**

-keepclassmembers class * {
    @org.springframework.beans.factory.annotation.Autowired *;
    @org.springframework.beans.factory.annotation.Value *;
}

-keep @javax.persistence.Entity class * { *; }
-keep @javax.persistence.Embeddable class * { *; }
-keep @javax.persistence.MappedSuperclass class * { *; }
-keepclassmembers class * {
    @javax.persistence.* <fields>;
    @javax.persistence.* <methods>;
}

-keepclassmembers,allowobfuscation class * {
    @org.springframework.beans.factory.annotation.Autowired <fields>;
    @org.springframework.beans.factory.annotation.Value <fields>;
}
-keep class com.eipl.amcs.config.HibernateConfig { *; }


-keep class com.eipl.amcs.json.** { *; }
-keep class com.eipl.amcs.controls.** { *; }

-keepclassmembers class * {
    @javafx.fxml.FXML *;
}

-dontwarn org.hibernate.**
-keep class org.hibernate.** { *; }
-keep class com.zaxxer.hikari.** { *; }
-keep class com.mysql.** { *; }
-keep interface com.mysql.cj.** { *; }

-keep class com.eipl.amcs.**

-keep public class com.eipl.amcs.base.controller.EmcsAppController { *; }
-keep interface * extends org.springframework.data.repository.Repository {
    <methods>;
}

-keep public class com.eipl.amcs.MainApp { *; }
-keep public class com.eipl.amcs.Launcher { *; }

-keep,allowobfuscation class com.eipl.amcs.** {
    <fields>;
    <methods>;
}