#server
server.port=8080
server.servlet.context-path=/eipl-amcs
#Batch insert
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true

#Database
spring.jpa.hibernate.ddl-auto=none
spring.datasource.url=jdbc:mysql://localhost:3366/eipl_amcs_db?characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=EAmcs2021
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true

#AMUL
#sync.url=http://streamamcs.emilkpro.in/eipl-amcs-processor/sync
#inbox.url=http://amulamcs.emilkpro.in/androiddpu/v1/master-data/inbox
#AMUL_OFFLINE
#sync.url=http://streamaamacss.emilkpro.in/eipl-amcs-processor/sync
#inbox.url=https://amulaamacss.yamatech.app/androiddpu/v1/master-data/inbox
#UAT
sync.url=http://amulamcsuat.emilkpro.in/eipl-amcs-processor/sync
inbox.url=http://amulamcsuat.emilkpro.in/androiddpu/v1/master-data/inbox 
debug=false
logging.level.root=INFO