baseurl=aHR0cDovL2xvY2FsaG9zdDo4MDgwL2VpcGwtYW1jcy8=
baseurl.realtime=aHR0cDovL2FtdWxhbWNzdWF0LmVtaWxrcHJvLmluL3dlYnNlcnZpY2UvYW1jcy92MS8=
app.request.debug=MA==
#Languages
app.languages=RW5nbGlzaCxHdWphcmF0aQ==
#Identity details
identity.union=MTAx
identity.society=MTAzMTg5Nw==
identity.dock=MTAzMTg5NzAx
identity.id=QUJD
identity.version=NC41
updater.url=aHR0cDovL2NsaWVudC5lbWlsa3Byby5pbi93ZWJzZXJ2aWNlL2VpcGwvdjEvZnJlZS1hY2Nlc3MvbGF0ZXN0LWFwcA==
identity.activation=QUJD
#Configurations
default.creditlimit=MTAwMDA=
ltr.to.kg=MS4wMw==
clr.const1=MC4yMQ==
clr.const2=MC42Ng==
default.snf=MQ==
deafult.snf.value=MA==
hrs=NzI=
qty.reading.rounding=MA==
quality.reading.rounding=MA==
sample.milk.size=MA==
accept.milktype.otherthen.default=MQ==
allow.multipleentry.samemilktype=MQ==
allow.multipleentry.diffmilktype=MQ==
member.collection.qty.mode=MA==
society.collection.qty.mode=MA==
milksale.qty.mode=MA==
dispatch.qty.mode=MQ==
receipt.qty.mode=MQ==
no.of.enter=MA==
no.of.enters.collection.slip=MA==
zero.amount.dispatch=MQ==
samplemilk=MQ==
avg.param.prev.shiftcount=NQ==
avg.param.capture=MA==
avg.param.capture.shift.value=Mw==
#Billing configuration
allow.billingmilkamountzero=MA==
allow.cashpayment=MQ==
#0-Society Bank, 1-Union Bank, 2-Local disburse
payment.mode=Mg==
#0-actual amount, 1-decimal truncate
payment.option=MA==
slip.language=ZW4=
backuppath=RDpcYmFja3Vw
masetting=U2luZ2xlIE1B
product.purchaserate=MA==
product.salerate=MA==
