baseurl=aHR0cDovL2xvY2FsaG9zdDo4MDgwL2VpcGwtYW1jcy8=
baseurl.realtime=aHR0cHM6Ly9hbXVsYW1jc2Jucy5lbWlsa3Byby5pbi8=
client.code=QkFOQVNfQU1DUw==
syncUrl.realtime=aHR0cDovLzQuMTg2LjI1LjEwMDo5NTAxL2VpcGwtYW1jcy1wcm9jZXNzb3Iv
app.request.debug=MA==
#Languages
app.languages=RW5nbGlzaCxHdWphcmF0aQ==
#Identity details
identity.union=MDAy
identity.society=MjAwMTAxMDUw
identity.dock=MjAwMTAxMDUwMDE=
identity.id=QUJD
identity.version=MS4z
identity.activation=QUJD
updater.url=aHR0cDovL2NsaWVudC5lbWlsa3Byby5pbi93ZWJzZXJ2aWNlL2VpcGwvdjEvZnJlZS1hY2Nlc3MvbGF0ZXN0LWFwcA==
#Configurations
default.creditlimit=MTAwMDAw
ltr.to.kg=MS4wMw==
clr.const1=MC4yMQ==
clr.const2=MC42Ng==
hrs=NzIwMDA=
default.snf=MA==
deafult.snf.value=MDE=
qty.reading.rounding=MA==
quality.reading.rounding=MA==
sample.milk.size=MQ==
accept.milktype.otherthen.default=MQ==
allow.multipleentry.samemilktype=MQ==
allow.multipleentry.diffmilktype=MQ==
member.collection.qty.mode=MA==
society.collection.qty.mode=MA==
milksale.qty.mode=MA==
dispatch.qty.mode=MQ==
receipt.qty.mode=MQ==
samplemilk=OTk5OQ==
no.of.enter=MQ==
no.of.enters.collection.slip=MQ==
zero.amount.dispatch=MQ==
avg.param.prev.shiftcount=NQ==
avg.param.capture=MA==
avg.param.capture.shift.value=NQ==
#Billing configuration
allow.billingmilkamountzero=MA==
allow.cashpayment=MQ==
#0-Society Bank, 1-Union Bank, 2-Local disburse
payment.mode=Mg==
#0-actual amount, 1-decimal truncate
payment.option=MA==
product.purchaserate=MA==
product.salerate=MA==
slip.language=RW5nbGlzaA==
application.language=R3VqYXJhdGk=
backuppath=RDpcYmFja3Vw
masetting=MQ==
decimalvalue=Mg==
variation.qty.block=MA==
variation.fat.block=MA==
variation.snf.block=MA==
variation.qty=MQ==
variation.fat=MQ==
variation.snf=MQ==
code.milktype.parsing=MA==
fifo.process=Zmlmbw==
variation.no.param=Mg==
slip.font=TmlybWFsYSBVSQ==
